Updated yaml files
camaraproject/WebRTC pull request #6
Opened 2023-11-06 08:10 UTC by pradeepachar-mavenir

- Updated RACM and CallHandling specifications.
- Notification Channel specification are added.

#### What type of PR is this?

Add one of the following kinds:
* bug
* correction
* enhancement/feature
* cleanup
* documentation
* subproject management
* tests

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for reviewers:

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

2023-11-06 08:20 UTC, pradeepachar-mavenir commented
@sushanthmavenir @TEF-RicardoSerr , please review the pull request.

2023-11-08 15:05 UTC, TEF-RicardoSerr commented
Hello, 

How would it fit the integration of other notification methods in the specifications? In the previous versions of the API, PNS was integrated in the RACM specification but it is no longer in any of these new specs. Would it be possible to include PNS in the new specification?

2023-11-10 04:08 UTC, pradeepachar-mavenir commented
> Hello,
> 
> How would it fit the integration of other notification methods in the specifications? In the previous versions of the API, PNS was integrated in the RACM specification but it is no longer in any of these new specs. Would it be possible to include PNS in the new specification?

In the new notification API, there is channelType defined, this can be extended to support new notification channels as requried.

2023-11-15 12:25 UTC, TEF-RicardoSerr commented
Do you find it feaseable to include PNS in this specification @pradeepachar-mavenir?

2023-11-17 02:50 UTC, deepakjaiswal1 commented
@pradeepachar-mavenir We should eliminate the use of userId within the CallHandling APIs, as users can be identified through the access/identification token.

Additionally, we should consider removing the responseCode from SessionInvitationNotification, SessionStatusNotification, and ReceiverStatusNotification. This information is redundant and could cause confusion for developers using the endpoints.

2023-11-17 03:14 UTC, deepakjaiswal1 commented
@pradeepachar-mavenir @TEF-RicardoSerr 

We firmly believe that the Channel service provider could function as an independent service rather than being integrated into the WebRTC GW. In our perspective, the RACM & channel APIs should follow this call-flow:

A) The client app initiates the creation of a channel (WebSocket).

POST /channels 
{
    "notificationChannel": {
        "channelType": "WebSockets",
        "channelData": {
            "maxNotifications": "1"
        },
        "clientCorrelator": "xyz123"
    }
}

HTTP/1.1 201 Created
{
    "notificationChannel": {
        "callbackURL": "http://example.com/callBackUrl/cbu112",
        "channelData": {
            "channelURL": "ws://example.com/exampleAPI/notificationchannel/v1/tel%3A%2B19585550100/channels/ch378/ws",
            "maxNotifications": "1"
        },
        "channelType": "WebSockets",
        "clientCorrelator": "xyz123",
        "resourceURL": "http://example.com/exampleAPI/notificationchannel/v1/tel%3A%2B19585550100/channels/ch378"
    }
}

B) Subsequently, the client app establishes an active session, providing the callback for the previously created notification channel.

POST /session
{
    "deviceId": "string",
    "notificationChannel": {
        "callbackURL": "http://example.com/callBackUrl/cbu112"
    }
}

HTTP/1.1 201 Created
{
    "clientId": "string",
    "resourceURL": "string"
}

The WebRTC GW posts client notifications using the callbackURL. By adopting this framework, the WebRTC GW is relieved from managing the intricacies of different notification channels. However, we need to consider cases where clients utilize multiple channels, such as a PNS channel for initial notification and a WebSocket channel for subsequent notifications.

We have two options to address this:
(A) Implement a combined channel for PNS + WebSocket, where the channel itself manages the logic to send notifications through the appropriate channel.
(B) Utilize multiple channels alongside a subscription model, where the client subscribes to specific events over each channel. We recommend option A.

2023-11-20 05:42 UTC, pradeepachar-mavenir commented
> @pradeepachar-mavenir We should eliminate the use of userId within the CallHandling APIs, as users can be identified through the access/identification token.
> 
> Additionally, we should consider removing the responseCode from SessionInvitationNotification, SessionStatusNotification, and ReceiverStatusNotification. This information is redundant and could cause confusion for developers using the endpoints.

2023-11-20 05:43 UTC, pradeepachar-mavenir commented
> #### Closed with unmerged commits

2023-11-28 20:23 UTC, deepakjaiswal1 commented
@pradeepachar-mavenir Appreciate the updated YAML files. The NotificationChannel schema lacks the necessary callbackURL for posting notifications on the channel. Could we include the callbackURL in the notification channel schema?

2023-11-29 03:44 UTC, pradeepachar-mavenir commented
> @pradeepachar-mavenir Appreciate the updated YAML files. The NotificationChannel schema lacks the necessary callbackURL for posting notifications on the channel. Could we include the callbackURL in the notification channel schema?

@deepakjaiswal1 In the RACM API, a new element notificationUri is added. The clients are expected to establish the notification channel with the notification server and include the callback uri provided by notification server in the notificationUri attribute.

2023-11-29 20:44 UTC, deepakjaiswal1 commented
@pradeepachar-mavenir We're good with the RACM API, and our feedback was regarding the Notification Channel API. The schema for the NotificationChannel, returned in the response body of the POST /channels request, should contain the callbackURL. This inclusion ensures that the implementation of notification channels outside of the WebRTC Gateway aligns with CAMARA specifications.

2023-12-05 12:27 UTC, TEF-RicardoSerr requested changes
Hello, just a few comments regarding the versioning and include o deepack error codes

2023-12-05 12:27 UTC, TEF-RicardoSerr commented on code/API_definitions/BYON-RACM-Service.yaml
> +          $ref: '#/components/responses/Generic400'
I suggest to include the Error codes defined by Deepak

```suggestion
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo'
              examples:
                400emergencyAdressMissing:
                  summary: Emergency address missing
                  value:
                    status: 400
                    code: EMERGENCY_ADDRESS_MISSING
                    message: Emergency address missing
                400genericResponse:
                  summary: Generic Response
                  value:
                    status: 400
                    code: INVALID_ARGUMENT
                    message: Schema validation failed at  ...
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo'
              examples:
                403maxRegistrationUser:
                  summary: Max registration per user
                  value:
                    status: 403
                    code: MAX_REGISTRATION_PER_USER
                    message: 'The maximum number of service registrations per user has been reached'
                403maxRegistrationMSISDN:
                  summary: Max registration per MSISDN
                  value:
                    status: 403
                    code: MAX_REGISTRATION_PER_MSISDN
                    message: 'The maximum number of service registrations per MSISDN has been reached'
                403maxDevicesUser:
                  summary: Max devices per user
                  value:
                    status: 403
                    code: MAX_DEVICES_PER_USER
                    message: 'The maximum number of device instances per user has been reached'
                403genericResponse:
                  summary: Generic Response
                  value:
                    status: 403
                    code: PERMISSION_DENIED
                    message: 'Operation not allowed: ...' 
```

2023-12-05 13:00 UTC, pradeepachar-mavenir commented on code/API_definitions/BYON-Notification-Channel.yaml
> +  version: 1.0.0
version changed to 0.1.0

2023-12-07 11:16 UTC, TEF-RicardoSerr approved these changes
we can come up with the first version

2023-12-07 11:16 UTC, merged